main:
  create_data: True
  debug: True
  feature_is_create: True
  feature_is_overwrite: True

mljar_params:
  results_path: "reports/AutoML_Debug"
  mode: "Perform"
  total_time_limit: 60
  explain_level: 2

cv:
  cv_num: 1