main:
  create_data: True
  debug: True
  feature_is_create: False
  feature_is_overwrite: False

mljar_params:
  results_path: "reports/AutoML_Debug"
  mode: "Perform"
  total_time_limit: 30
  explain_level: 2

cv:
  cv_num: 1