main:
  create_data: True

mljar_params:
  results_path: "reports/AutoML_Debug"
  mode: "Compete"
  total_time_limit: 300
  explain_level: 2

cv:
  cv_num: 1

discriminator:
  ndf: 64

disc_adam:
  learning_rate: 0.0002
  beta_1: 0.5

generator:
  ngf: 64
  input_dim: 64

dcgan_adam:
  learning_rate: 0.0002
  beta_1: 0.5

tricked_generator_adam:
  learning_rate: 0.002
  beta_1: 0.5

tricked_gan_adam:
  learning_rate: 0.0002
  beta_1: 0.5

dcgan_training:
  batch_size: 32
  num_epochs: 400

anogan_training:
  anogan_epochs: 200
  anogan_batch_size: 4
  anogan_is_normal: False
