main:
  create_data: True
  debug: False
  feature_is_create: False
  feature_is_overwrite: False

mljar_params:
  results_path: "reports/AutoML_0310_Perform_With_Proper_Seeds"
  mode: "Perform"
  total_time_limit: 1200
  explain_level: 2

cv:
  cv_num: 1